/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sam
 */
public class ventanaCRUDEAlumos extends javax.swing.JFrame {

        /**
         * Creates new form ventanaCRUDEAlumos
         */
        public ventanaCRUDEAlumos() {
                initComponents();
                mostrarDatos("");

                this.setLocationRelativeTo(null);
                this.setTitle("Registrar Alumno");
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPopupMenu1 = new javax.swing.JPopupMenu();
                jMenuItem1 = new javax.swing.JMenuItem();
                btnAgregarAlumno = new javax.swing.JButton();
                btnModificarAlumno = new javax.swing.JButton();
                btnEliminarAlumno = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblAlumnos = new javax.swing.JTable();
                lblDescripcion = new javax.swing.JLabel();
                txtIdAlumno = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                txtNombreAlumno = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtApellidoAlumno = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtNivel = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                btnBuscar = new javax.swing.JButton();
                txtBusqueda = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                btnMostrar = new javax.swing.JButton();
                btnRegresar = new javax.swing.JButton();

                jMenuItem1.setText("Modificar");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                        }
                });
                jPopupMenu1.add(jMenuItem1);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnAgregarAlumno.setText("Agregar");
                btnAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAgregarAlumnoActionPerformed(evt);
                        }
                });

                btnModificarAlumno.setText("Modificar");
                btnModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarAlumnoActionPerformed(evt);
                        }
                });

                btnEliminarAlumno.setText("Eliminar");
                btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarAlumnoActionPerformed(evt);
                        }
                });

                tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

                }, new String[] {

                }));
                tblAlumnos.setComponentPopupMenu(jPopupMenu1);
                jScrollPane1.setViewportView(tblAlumnos);

                lblDescripcion.setText("Ventana para agregar a los alumnos");

                jLabel1.setText("Identificador");

                jLabel2.setText("Nombre");

                jLabel3.setText("Apellido");

                jLabel4.setText("Nivel");

                btnBuscar.setText("Buscar");
                btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarActionPerformed(evt);
                        }
                });

                jLabel5.setText("Nombre");

                btnMostrar.setText("Mostar");
                btnMostrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMostrarActionPerformed(evt);
                        }
                });

                btnRegresar.setText("Regresar");
                btnRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegresarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtIdAlumno,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                101,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(jLabel1)))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(txtNombreAlumno,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                101,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtApellidoAlumno,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                103,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txtNivel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                97,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                55,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(52, 52, 52)
                                                                                                .addComponent(jLabel3)
                                                                                                .addGap(82, 82, 82)
                                                                                                .addComponent(jLabel4)
                                                                                                .addGap(32, 32, 32))))
                                                .addGroup(layout.createSequentialGroup().addGap(84, 84, 84)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnAgregarAlumno,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                95,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(35, 35, 35)
                                                                                                .addComponent(btnModificarAlumno,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                95,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(33, 33, 33)
                                                                                                .addComponent(btnMostrar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                93,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(30, 30, 30)
                                                                                                .addComponent(btnEliminarAlumno,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                95,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1)))
                                                .addGroup(layout.createSequentialGroup().addGap(214, 214, 214)
                                                                .addComponent(lblDescripcion)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(103, 103, 103))
                                .addGroup(layout.createSequentialGroup().addGap(25, 25, 25).addComponent(btnRegresar)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5)
                                                                                .addGap(289, 289, 289))
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGap(53, 53, 53)
                                                                                .addComponent(btnBuscar,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                91,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(37, 37, 37)
                                                                                .addComponent(txtBusqueda,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                103,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)))));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(32, 32, 32).addComponent(lblDescripcion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37,
                                                                Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnAgregarAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnModificarAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnEliminarAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnMostrar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                37,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(txtIdAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtNombreAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtApellidoAlumno,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtNivel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel4))
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGap(39, 39, 39)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(btnBuscar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                37,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(txtBusqueda,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel5)
                                                                                .addContainerGap())
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btnRegresar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                33,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)))));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarAlumnoActionPerformed
                // agregar();
                Conexion conexion = new Conexion();
                Connection connection = conexion.obtenerConexion();
                try {
                        // String sql = " INSERT INTO alumno (idAlumno, nombreAlumno, apellidoAlumno,
                        // nivel) VALUES (?,?,?,?) ";
                        PreparedStatement preparedstatement = connection.prepareStatement(
                                        " INSERT INTO alumno (idAlumno, nombreAlumno, apellidoAlumno, nivel, idProfesor) VALUES (?,?,?,?,?) ");
                        preparedstatement.setString(1, txtIdAlumno.getText());
                        preparedstatement.setString(2, txtNombreAlumno.getText());
                        preparedstatement.setString(3, txtApellidoAlumno.getText());
                        preparedstatement.setInt(4, 4);

                        preparedstatement.setInt(5, Variables.idProfesor);

                        preparedstatement.executeUpdate();

                        mostrarDatos("");
                } catch (SQLException ex) {
                        ex.printStackTrace();

                }

        }// GEN-LAST:event_btnAgregarAlumnoActionPerformed

        private void btnModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarAlumnoActionPerformed
                Conexion conexion = new Conexion();
                Connection connection = conexion.obtenerConexion();
                try {
                        PreparedStatement preparedstatement = connection.prepareStatement(
                                        "UPDATE alumno SET nombreAlumno = ?, apellidoAlumno =?, nivel = ? WHERE idAlumno = ? ");
                        preparedstatement.setString(4, txtIdAlumno.getText());
                        preparedstatement.setString(1, txtNombreAlumno.getText());
                        preparedstatement.setString(2, txtApellidoAlumno.getText());
                        preparedstatement.setInt(3, Integer.parseInt(txtNivel.getText()));
                        preparedstatement.executeUpdate();
                        mostrarDatos("");
                } catch (Exception e) {
                        System.out.println(e.getMessage());
                }

        }// GEN-LAST:event_btnModificarAlumnoActionPerformed

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
                // TODO add your handling code here:
                mostrarDatos(txtBusqueda.getText());
        }// GEN-LAST:event_btnBuscarActionPerformed

        private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMostrarActionPerformed
                // TODO add your handling code here:
                mostrarDatos("");
        }// GEN-LAST:event_btnMostrarActionPerformed

        private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
                // TODO add your handling code here:
                int fila = tblAlumnos.getSelectedRow();
                if (fila >= 0) {
                        txtIdAlumno.setText(tblAlumnos.getValueAt(fila, 0).toString());
                        txtNombreAlumno.setText(tblAlumnos.getValueAt(fila, 1).toString());
                        txtApellidoAlumno.setText(tblAlumnos.getValueAt(fila, 2).toString());
                        txtNivel.setText(tblAlumnos.getValueAt(fila, 3).toString());
                } else {
                        JOptionPane.showMessageDialog(null, "No seleccionaste alguna fila");
                }
        }// GEN-LAST:event_jMenuItem1ActionPerformed

        private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarAlumnoActionPerformed
                // TODO add your handling code here:
                Conexion conexion = new Conexion();
                Connection connection = conexion.obtenerConexion();

                int fila = tblAlumnos.getSelectedRow();
                String cod = "";
                cod = tblAlumnos.getValueAt(fila, 0).toString();

                try {
                        PreparedStatement preparedstatement = connection
                                        .prepareStatement("DELETE FROM alumno WHERE idAlumno = ?");
                        preparedstatement.setString(1, cod);
                        preparedstatement.executeUpdate();
                        mostrarDatos("");
                } catch (Exception e) {

                }
        }// GEN-LAST:event_btnEliminarAlumnoActionPerformed

        private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegresarActionPerformed
                ventanaOpcionesProfesor voProfesor = new ventanaOpcionesProfesor();
                voProfesor.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_btnRegresarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAgregarAlumno;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JButton btnEliminarAlumno;
        private javax.swing.JButton btnModificarAlumno;
        private javax.swing.JButton btnMostrar;
        private javax.swing.JButton btnRegresar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblDescripcion;
        private javax.swing.JTable tblAlumnos;
        private javax.swing.JTextField txtApellidoAlumno;
        private javax.swing.JTextField txtBusqueda;
        private javax.swing.JTextField txtIdAlumno;
        private javax.swing.JTextField txtNivel;
        private javax.swing.JTextField txtNombreAlumno;
        // End of variables declaration//GEN-END:variables

        private void mostrarDatos(String valor) {
                Conexion conexion = new Conexion();
                Connection connection = conexion.obtenerConexion();

                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("Identificador");
                modelo.addColumn("Nombre");
                modelo.addColumn("Apellido");
                modelo.addColumn("Nivel");
                tblAlumnos.setModel(modelo);
                String sql = " ";
                if (valor.equals("")) {
                        sql = " SELECT * FROM alumno ";
                } else {
                        sql = " SELECT * FROM alumno WHERE idAlumno = '" + valor + "'";
                }

                String[] datos = new String[4];

                try {
                        Statement statement = connection.createStatement();
                        ResultSet resultset = statement.executeQuery(sql);
                        while (resultset.next()) {
                                datos[0] = resultset.getString(1);
                                datos[1] = resultset.getString(2);
                                datos[2] = resultset.getString(3);
                                datos[3] = resultset.getString(4);
                                modelo.addRow(datos);
                        }
                        tblAlumnos.setModel(modelo);
                } catch (Exception e) {

                }
        }
}
