/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Locale;

/**
 *
 * @author sam
 */
public class ventanaOpcionesProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ventanaOpcionesProfesor
     */
    public ventanaOpcionesProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Opciones del Profesor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescripcion = new javax.swing.JLabel();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnMostrarResultado = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDescripcion.setText("Editas el registro de tus alumnos");

        btnRegistrarAlumno.setText("Registrar alumnos");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });

        btnMostrarResultado.setText("Mostrar resultados");
        btnMostrarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarResultadoActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(191, 191, 191).addComponent(lblDescripcion))
                        .addGroup(layout.createSequentialGroup().addGap(215, 215, 215)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnRegistrarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMostrarResultado, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(btnRegresar)))
                .addContainerGap(172, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(65, 65, 65).addComponent(lblDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnMostrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarResultadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMostrarResultadoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnMostrarResultadoActionPerformed

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        ventanaCRUDEAlumos vCRUDE = new ventanaCRUDEAlumos();
        vCRUDE.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegresarActionPerformed
        ventaInicio vInicio = new ventaInicio();
        vInicio.setVisible(true);
        this.dispose();

    }// GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarResultado;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblDescripcion;
    // End of variables declaration//GEN-END:variables
}
